### ISSUE TITLE
Using a precomputed brainmask

### ISSUE THREAD

**Issue by rcruces** [SCAN-NRAD/DL-DiReCT#1]
Hi,

Is it possible to run the algorithm using a pre-computed brain mask?

**Comment by mrunibe** [comment]
Yes, if the brain mask is already applied (i.e. the input is already brain extracted), you may just run DL+DiReCT **without** the --bet option.

Otherwise, you first have to mask the input with the brain mask. Something like:

`mri_mask T1.nii.gz brainmask.nii.gz T1_noskull.nii.gz`

Then run DL+DiReCT on T1_noskull.nii.gz. If you do not have the _mri_mask_ command available, you may use a few lines of python to apply it (see [example](https://github.com/SCAN-NRAD/DL-DiReCT/blob/72220096524bea9dd757f989c73b5832b57f6689/src/bet.py#L85)).

**Comment by rcruces** [comment]
thank you
